### PR TITLE
merge in tested examples from Tsvi's repo; DAT-6679

### PR DESCRIPTION
**Pull request by ap-liquibase**
Finished testing individual examples from  in this new folder layout. By default all examples run `on: push` trigger. Added som info into top-level README

### CODE REVIEW

**Review by XDelphiGrl — CHANGES_REQUESTED** [review]
@ap-liquibase, hello!

* Do you mean to have *.bin, *.jar, *.jar.original and *.lock files as part of this PR?
* Is gc.properties intended to be an empty file?
* Please remove the artifacts generated by the build; nothing in the target directory should be committed. @jnewton03, please confirm this for @ap-liquibase and me.

Another thing I notice is that in the  liquibase-github-action-example/example/changelogs/configurationValues.txt , the username is "liqubase" (missing the letter i). The liquibase.properties files specify the username as "liquibase" (with the i). Do the examples work with the mismatched username? I'm not sure how all the code fits together so perhaps the username is coming from a different location in the extras. 


Thanks for all the work you put into this!!

**Comment by ap-liquibase** [comment]
@XDelphiGrl Hi.
To address your last observation. All the examples are independent with their own Liquibase configurations and databases. The default example in liquibase-github-action-example/example/ has the missing "i" in the username which matches what the db expects for connectivity. I have re-verified this. But I'm glad you asked about it because I will need to change README to tell folks that they need to store the passwords in [GitHub Secrets](https://docs.github.com/en/actions/reference/encrypted-secrets) for the default example

**Comment by ap-liquibase** [comment]
@XDelphiGrl 
Regarding *.jar files, I think the file `./example/changelogs/ojdbc8.jar` was intentionally uploaded into the repo by @adeelmalik78 to support testing the official GH Action with Oracle. 

For the other file types I've reached out to Tsvi to ask:

"Do you know if the following can be removed from the consolidated examples repo, or are they needed to properly run the examples? (We want to ship a clean repo without intermediate artifacts)"
```
./SalesManager_h2_version/target/SalesManager-0.0.1-SNAPSHOT.jar
./SalesManager_h2_version/target/SalesManager-0.0.1-SNAPSHOT.jar.original
./Gradle_h2/.gradle/checksums/md5-checksums.bin
./Gradle_h2/.gradle/checksums/sha1-checksums.bin
./Gradle_h2/.gradle/6.5/executionHistory/executionHistory.bin
./Gradle_h2/.gradle/6.5/fileChanges/last-build.bin
```

**Comment by ap-liquibase** [comment]
I've reached out to @szandany regarding gc.properties being empty. Will remove them if they're not needed

**Comment by jnewton03** [comment]
@ap-liquibase I believe @XDelphiGrl is correct that the target dirs (compiled code) should not be checked in.  I wonder if these were accidental on the previous repo.

**Comment by XDelphiGrl** [comment]
> 
> 
> @XDelphiGrl
> Regarding *.jar files, I think the file `./example/changelogs/ojdbc8.jar` was intentionally uploaded into the repo by @adeelmalik78 to support testing the official GH Action with Oracle.
> 
> For the other file types I've reached out to @szandany to ask:
> 
> "Do you know if the following can be removed from the consolidated examples repo, or are they needed to properly run the examples? (We want to ship a clean repo without intermediate artifacts)"
> 
> ```
> ./SalesManager_h2_version/target/SalesManager-0.0.1-SNAPSHOT.jar
> ./SalesManager_h2_version/target/SalesManager-0.0.1-SNAPSHOT.jar.original
> ./Gradle_h2/.gradle/checksums/md5-checksums.bin
> ./Gradle_h2/.gradle/checksums/sha1-checksums.bin
> ./Gradle_h2/.gradle/6.5/executionHistory/executionHistory.bin
> ./Gradle_h2/.gradle/6.5/fileChanges/last-build.bin
> ```

Thanks for following up. The Oracle driver jar makes sense to keep. The others, perhaps not so much.

**Comment by XDelphiGrl** [comment]
> 
> 
> I've reached out to @szandany regarding gc.properties being empty. Will remove them if they're not needed

Thank you!

**Review by XDelphiGrl — APPROVED** [review]
Thanks for cleaning up the commit, @ap-liquibase. Thank you even more for doing the work of combining our various examples into one repository. Approved!

**Pull request merged**
